web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 60

templates:
  transmissionrpc:
    transmission:
      host: transmission
      port: 9091
      username: torrente
      password: "PASSWORD"

  tv:
    regexp:
      reject:
        - x265: {from: title}
    series:
      settings:
        tv:
          exact: yes
          propers: 12 hours
          quality: 720p
      group:
        - The Walking Dead:Dead City
        - Silo:
            begin: S01E10
        - The Outsider

tasks:
  showrss:
    rss: https://showrss.info/other/all.rss
    priority: 1
    all_series: yes
    template:
      - tv
      - transmissionrpc
    set:
      path: /downloads/complete

  showrss_outsider:
    rss: https://showrss.info/show/1249.rss
    template:
      - tv
      - transmissionrpc
    set:
      path: /downloads/complete

  showrss_silo:
    rss: https://showrss.info/show/1675.rss
    template:
      - tv
      - transmissionrpc
    set:
      path: /downloads/complete

  sort-series:
    metainfo_series: yes
    accept_all: yes
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    template: tv
    series:
      settings:
        group:
          parse_only: yes
    require_field: series_name
    move:
      to: '/storage/{{series_name}}'
      rename: '{{series_name}} - S{{series_season|pad(2)}}E{{series_episode|pad(2)}}'

  remove stale torrents:
    from_transmission:
      only_complete: yes
      host: transmission
      port: 9091
      username: torrente
      password: "password"
    disable: [seen, seen_info_hash]
    if:
      - transmission_progress == 100: accept
      - not transmission_seed_ratio_ok: reject
      - not transmission_idle_limit_ok: reject
    transmission:
      host: transmission
      port: 9091
      username: torrente
      password: "password"
      action: purge
