web_server: 
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules: 
  - tasks: '*'
    interval:
      minutes: 60

templates:
  transmission:
    transmission:
      host: IP/HOSTNAME
      port: PORT
      include_subs: yes
      path: /downloads/complete

tasks:
  eztv:
    rss: https://eztv.io/ezrss.xml
    template: transmission
    series:
      - Lovecraft Country
    quality: 720p

  argenteam:
    rss: ARGENTEAM_TOKEN
    template: transmission
    series:
      - The 100
    quality: 720p  
  
# CMD
# flexget web passwd PASSWORD        
# flexget check
# flexget --test execute
# flexget daemon reload-config
# flexget history
# flexget series list
# flexget series forget "SERIE"
