---
version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: trans-flex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - USER=$USER
      - PASS=$PASS
    volumes:
      - $HOME/transmission/config:/config
      - $HOME/transmission/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  flexget:
    image: wiserain/flexget
    volumes:
      - $HOME/transmission/flexget:/config
      - $HOME/transmission/torrents:/downloads
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
    restart: unless-stopped
    links:
      - transmission