---
version: '3.7'
networks:
  media-net:
    name: media-net
    driver: bridge

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    networks:
      - media-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - USER=torrente
      - PASS=password
    volumes:
      - ~/datos/transmission/config:/config
      - ~/datos/transmission:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - media-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ~/datos/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ~/datos/radarr/config:/config
      - ~/datos/jellyfin/media:/movies
      - ~/datos/transmission/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ~/datos/sonarr/config:/config
      - ~/datos/jellyfin/series:/tvshows
      - ~/datos/transmission/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - media-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ~/datos/bazarr/config:/config
      - ~/datos/jellyfin/media:/movies
      - ~/datos/jellyfin/series:/tvshows
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:1.9.0
    container_name: jellyseerr
    networks:
      - media-net
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - 5055:5055
    volumes:
      - ~/datos/jellyseer:/app/config
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:10.9.8
    container_name: jellyfin
    networks:
      - media-net
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ~/datos/jellyfin/config:/config:rw
      - ~/datos/jellyfin/media:/movies
      - ~/datos/jellyfin/series:/tvshows
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - media-net
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - ${PORT:-8191}:8191
    restart: unless-stopped

# cli
# docker-compose up -d --force-recreate --no-deps --remove-orphans jellyseerr
